version: '3.9'

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:0.14
    ports:
      - "4566-4620:4566-4620"
    environment:
      - DEBUG=1
      - SERVICES=s3,lambda,ssm
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_DOCKER_NETWORK=localstack_development
    networks:
      - development
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  development:
